image:
  repository: your-registry.example.com/pharmacy/insurer-integration-service
  tag: "0.0.1"
  pullPolicy: IfNotPresent

replicas: 1
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
ingress:
  enabled: false
extraEnv: []
