version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pos-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/create-dbs.sql:/docker-entrypoint-initdb.d/10-create-dbs.sql:ro

  redis:
    image: redis:7
    container_name: pos-redis
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: pos-redpanda
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpandadata:/var/lib/redpanda/data

volumes:
  pgdata:
  redisdata:
  redpandadata:
