apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector: { matchLabels: { app: redpanda } }
  template:
    metadata: { labels: { app: redpanda } }
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.redpanda.image }}
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - 512M
            - --reserve-memory
            - 0M
            - --node-id
            - "0"
            - --check=false
          ports:
            - containerPort: 9092
            - containerPort: 9644
          volumeMounts:
            - { name: redpandadata, mountPath: /var/lib/redpanda/data }
      volumes:
        - name: redpandadata
          persistentVolumeClaim:
            claimName: redpanda-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector: { app: redpanda }
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: admin
      port: 9644
      targetPort: 9644
