# --- Build stage ---
FROM maven:3.9-eclipse-temurin-24 AS build
ARG MODULE
WORKDIR /workspace
COPY . .
RUN mvn -q -DskipTests -pl ${MODULE} -am package

# --- Run stage ---
FROM eclipse-temurin:24-jre
ARG MODULE
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75 -XX:+UseSerialGC"
WORKDIR /app
COPY --from=build /workspace/${MODULE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
